AWSTemplateFormatVersion: '2010-09-09'
Description: Amplify App connected to GitHub with Cognito environment variables

Parameters:
  GitHubRepo:
    Type: String
    Description: GitHub repository # (format: username/reponame)
  GitHubBranch:
    Type: String
    Default: main
    Description: Branch to connect # (default: main)
  GitHubToken:
    Type: String
    NoEcho: true
    Description: Personal Access Token for GitHub # (with repo permissions)
  UserPoolId:
    Type: String
    Description: Cognito User Pool ID
  UserPoolClientId:
    Type: String
    Description: Cognito User Pool Client ID

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub "${AWS::StackName}-amplify-app"
      Repository: !Sub "https://github.com/${GitHubRepo}"
      OauthToken: !Ref GitHubToken
      EnvironmentVariables:
        - Name: USER_POOL_ID
          Value: !Ref UserPoolId
        - Name: USER_POOL_CLIENT_ID
          Value: !Ref UserPoolClientId
      BuildSpec: |
        version: 1
        backend:
          phases:
            preBuild:
              commands:
                - npm install
            build:
              commands:
                - echo "No build step required for Express backend"
          artifacts:
            baseDirectory: /
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref GitHubBranch
      EnableAutoBuild: true
      EnvironmentVariables:
        - Name: USER_POOL_ID
          Value: !Ref UserPoolId
        - Name: USER_POOL_CLIENT_ID
          Value: !Ref UserPoolClientId

Outputs:
  AmplifyAppId:
    Description: Amplify App ID
    Value: !GetAtt AmplifyApp.AppId
  AmplifyAppDefaultDomain:
    Description: Amplify App Default Domain
    Value: !GetAtt AmplifyApp.DefaultDomain
  AmplifyBranchUrl:
    Description: Deployed Branch URL
    Value: !Sub "https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}"