version: 1
backend:
  phases:
    preBuild:
      commands:
        - echo "Configuring Git to suppress detached HEAD warnings"
        - git config advice.detachedHead false
        - echo "Fetching full branch history"
        - git fetch --unshallow || true
        - git checkout main || true
        - git pull origin main || true
        - echo "Installing Node.js dependencies"
        - npm install -g aws-sam-cli
        - npm install
    build:
      commands:
        - echo "Building SAM project"
        - sam build
    postBuild:
      commands:
        - echo "Deploying SAM stack"
        - sam deploy --no-confirm-changeset \
                     --no-fail-on-empty-changeset \
                     --stack-name amplify-backend \
                     --s3-bucket $DEPLOYMENT_BUCKET_NAME \
                     --capabilities CAPABILITY_IAM
artifacts:
  files:
    - '**/*'

