version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
s3_prefix = "sam-app"
resolve_s3 = true
region = "ap-south-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=\"dev\" GoogleClientId=\"769612641054-ekvfq9je0rbupoco8ekg58lhfv9tubqn.apps.googleusercontent.com\" GitHubRepo=\"patelhardikp6/Cognito_Backend\" GitHubBranch=\"main\" UserPoolId=\"ap-south-1_3dcWs4KFM\" UserPoolClientId=\"5qse1piq58gpp1afnr2u8443ck\" FrontendUrl=\"http://localhost:4000\""
confirm_changeset = true
disable_rollback = true
image_repositories = []

